// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truco_API.Data;

#nullable disable

namespace Truco_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250828004427_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Truco_API.Models.Jogador", b =>
                {
                    b.Property<int>("codJogador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codJogador"));

                    b.Property<string>("nomeJogador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroVitorias")
                        .HasColumnType("int");

                    b.HasKey("codJogador");

                    b.ToTable("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
